package View;


//All internal import
import Controller.AppCommandMessage_CopyAndSaveXMLFile;
import Controller.AppCommandMessage_LoadCryptoJSON;
import Controller.AppCommandMessage_LoadKMyMoneyXML;
import Controller.AppCommandMessage_LoadUSDCAD;
import Controller.IControllerApp;


public class JFrame_Main extends javax.swing.JFrame  implements IView{
	private IControllerApp m_objController;
    private final javax.swing.JTextField[] m_arFldCryptosValue;
    private final javax.swing.JTextField[] m_arFldKmyMoneyXMLLatestValue;

    /**
     * Creates new form JFrame_Main
     */
    public JFrame_Main() {
        initComponents();
        
        m_arFldCryptosValue= new javax.swing.JTextField[6];
        m_arFldCryptosValue[0]= m_fldBitcoinValue;
        m_arFldCryptosValue[1]= m_fldBitcoinCashValue;
        m_arFldCryptosValue[2]= m_fldBitcoinGoldValue;
        m_arFldCryptosValue[3]= m_fldEthereumValue;
        m_arFldCryptosValue[4]= m_fldLitecoinValue;
        m_arFldCryptosValue[5]= m_fldIOTAValue;

        m_arFldKmyMoneyXMLLatestValue= new javax.swing.JTextField[6];
        m_arFldKmyMoneyXMLLatestValue[0]= m_fldXMLBitcoinValue;
        m_arFldKmyMoneyXMLLatestValue[1]= m_fldXMLBitcoinCashValue;
        m_arFldKmyMoneyXMLLatestValue[2]= m_fldXMLBitcoinGoldValue;
        m_arFldKmyMoneyXMLLatestValue[3]= m_fldXMLEthereumValue;
        m_arFldKmyMoneyXMLLatestValue[4]= m_fldXMLLitecoinValue;
        m_arFldKmyMoneyXMLLatestValue[5]= m_fldXMLIOTAValue;
        
        setVisible(true);
    }

    @Override
    public void setController(IControllerApp p_objController){
		m_objController= p_objController;
	}

    @Override
    public void setUSDValue(double p_fValue){
		m_fldUSDValue.setText(String.format("%f", p_fValue));
	}

    @Override
    public void setCryptoIdxValue(int p_nIdx, double p_fValue){
		m_arFldCryptosValue[p_nIdx].setText(String.format("%f", p_fValue));
	}

    @Override
    public void setXMLIdxValue(int p_nIdx, double p_fValue){
		m_arFldKmyMoneyXMLLatestValue[p_nIdx].setText(String.format("%f", p_fValue));
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        m_btStepOneLoadUSDValue = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        m_fldUSDValue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        m_fldBitcoinValue = new javax.swing.JTextField();
        m_fldBitcoinCashValue = new javax.swing.JTextField();
        m_fldEthereumValue = new javax.swing.JTextField();
        m_fldLitecoinValue = new javax.swing.JTextField();
        m_fldIOTAValue = new javax.swing.JTextField();
        m_fldXMLBitcoinValue = new javax.swing.JTextField();
        m_fldXMLBitcoinCashValue = new javax.swing.JTextField();
        m_fldXMLEthereumValue = new javax.swing.JTextField();
        m_fldXMLLitecoinValue = new javax.swing.JTextField();
        m_fldXMLIOTAValue = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        m_fldBitcoinGoldValue = new javax.swing.JTextField();
        m_fldXMLBitcoinGoldValue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        m_btStepOneLoadUSDValue.setText("1.GetUSD");
        m_btStepOneLoadUSDValue.setFocusable(false);
        m_btStepOneLoadUSDValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        m_btStepOneLoadUSDValue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        m_btStepOneLoadUSDValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed_Step1LoadUSDCAD(evt);
            }
        });
        jToolBar1.add(m_btStepOneLoadUSDValue);

        jButton13.setText("2.GetCrypto");
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed_Step2GetCryptoRecords(evt);
            }
        });
        jToolBar1.add(jButton13);

        jButton14.setText("3.GetFile");
        jButton14.setFocusable(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed_Step3GetXMLFile(evt);
            }
        });
        jToolBar1.add(jButton14);

        jButton15.setText("4.CopySaveFile");
        jButton15.setFocusable(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed_Step4CopySaveFile(evt);
            }
        });
        jToolBar1.add(jButton15);

        jLabel1.setText("USD to CAD multiplier: ");

        jLabel2.setText("ONLINE");

        jLabel3.setText("KMyMoney File");

        jLabel4.setText("Bitcoin");

        jLabel5.setText("Bitcoin Cash");

        jLabel6.setText("Ethereum");

        jLabel7.setText("Litecoin");

        jLabel8.setText("IOTA");

        jLabel9.setText("Bitcoin Gold");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(73, 73, 73)
                                        .addComponent(m_fldBitcoinValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m_fldXMLBitcoinValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m_fldUSDValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(34, 34, 34)
                        .addComponent(m_fldBitcoinCashValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(m_fldXMLBitcoinCashValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(37, 37, 37)
                        .addComponent(m_fldBitcoinGoldValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(m_fldXMLBitcoinGoldValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(53, 53, 53)
                        .addComponent(m_fldEthereumValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(m_fldXMLEthereumValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(65, 65, 65)
                        .addComponent(m_fldLitecoinValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(m_fldXMLLitecoinValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(87, 87, 87)
                        .addComponent(m_fldIOTAValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(m_fldXMLIOTAValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(m_fldUSDValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(m_fldBitcoinValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_fldXMLBitcoinValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(m_fldBitcoinCashValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_fldXMLBitcoinCashValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(m_fldBitcoinGoldValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_fldXMLBitcoinGoldValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(m_fldEthereumValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_fldXMLEthereumValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(m_fldXMLLitecoinValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(m_fldLitecoinValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(m_fldXMLIOTAValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_fldIOTAValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActionPerformed_Step1LoadUSDCAD(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPerformed_Step1LoadUSDCAD
        m_objController.notify(new AppCommandMessage_LoadUSDCAD(this, m_objController));
    }//GEN-LAST:event_ActionPerformed_Step1LoadUSDCAD

    private void ActionPerformed_Step2GetCryptoRecords(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPerformed_Step2GetCryptoRecords
        m_objController.notify(new AppCommandMessage_LoadCryptoJSON(this, m_objController));
    }//GEN-LAST:event_ActionPerformed_Step2GetCryptoRecords

    private void ActionPerformed_Step3GetXMLFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPerformed_Step3GetXMLFile
        m_objController.notify(new AppCommandMessage_LoadKMyMoneyXML(this, m_objController));
    }//GEN-LAST:event_ActionPerformed_Step3GetXMLFile

    private void ActionPerformed_Step4CopySaveFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPerformed_Step4CopySaveFile
        m_objController.notify(new AppCommandMessage_CopyAndSaveXMLFile(this, m_objController));
    }//GEN-LAST:event_ActionPerformed_Step4CopySaveFile


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton m_btStepOneLoadUSDValue;
    private javax.swing.JTextField m_fldBitcoinCashValue;
    private javax.swing.JTextField m_fldBitcoinGoldValue;
    private javax.swing.JTextField m_fldBitcoinValue;
    private javax.swing.JTextField m_fldEthereumValue;
    private javax.swing.JTextField m_fldIOTAValue;
    private javax.swing.JTextField m_fldLitecoinValue;
    private javax.swing.JTextField m_fldUSDValue;
    private javax.swing.JTextField m_fldXMLBitcoinCashValue;
    private javax.swing.JTextField m_fldXMLBitcoinGoldValue;
    private javax.swing.JTextField m_fldXMLBitcoinValue;
    private javax.swing.JTextField m_fldXMLEthereumValue;
    private javax.swing.JTextField m_fldXMLIOTAValue;
    private javax.swing.JTextField m_fldXMLLitecoinValue;
    // End of variables declaration//GEN-END:variables
}
